### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by Ste74** [biglinux/usb-dirty-pages-udev#1]
Hi @bigbruno , can you please put the license somewhere? I see you put into PKGBUILD a GPL3 charge but is it possible to specify also in the repository?
Or at last put in the script like this for GPL3
https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/bin/buildpkg.in 

Thank you 
Stefano Capitani

**Comment by bigbruno** [comment]
In smaller scripts sometimes I forget to specify the license, solved.

**Comment by Ste74** [comment]
Thank you mate
